### ISSUE TITLE
Enable coverage comparison

### ISSUE THREAD

**Issue by LGro** [boschresearch/blackboxopt#115]
With the coverage reporting action we still get the following note:
> No coverage data of the default branch was found for comparison. A possible reason for this is that the coverage action has not yet run after a push event and the data is therefore not yet initialized.

Enable storing the coverage in the respective branch to allow the comparison in each PR.

Could it be that the following line points to a non existing step output because the step names changed between the example and our implementation?
https://github.com/boschresearch/blackboxopt/blob/main/.github/workflows/python.yaml#L85

**Comment by dynobo** [comment]
To me it seems like everything is fine with the naming.

If I understand this action correctly, it works by [publishing some helper files into a helper branch](https://github.com/py-cov-action/python-coverage-comment-action#default-branch-mode), but this is only the case if it runs on `main`. Currently, the `report` stage seems to be [skipped on `main`](https://github.com/boschresearch/blackboxopt/actions/runs/5855840316), which probably led to this helper branch [not being created in the first place](https://github.com/boschresearch/blackboxopt/branches). I think that would explain the warning mentioned above. 

Therefore, I think just removing the run-limitation of the `report` stage on PRs should fix this, and propose #121,
